### ISSUE TITLE
Отображение почасового прогноза погоды

### ISSUE THREAD

**Issue by il77781** [yandex/pogoda-home-assistant#10]
Сейчас у меня прогноз погоды на ближайшие 48 часов отображается с "шагом" 5, 6 и 7 часов... При этом в "песочнице" в личном кабинете прогноз погоды можно получить с "шагом" 1 час...
У всех так?
И можно ли это как-то изменить? Например, добавить настройку, позволяющую изменять этот "шаг"... Думаю, это могло бы быть полезно...

**Comment by il77781** [comment]
Уважаемые разработчики, прошу Вас хоть как-то отреагировать на поднятые мною вопросы... ) В конце концов, даже отрицательный ответ - тоже ответ: если не считаете нужным ничего исправлять/добавлять, то ведь можно просто честно об этом заявить, правда ведь? )

**Comment by dimastark** [comment]
Да, мы уже рассмотрели все issue, закрыли те, которые были не актуальные.
Если ваш issue сейчас открыт, то вероятно, мы подумаем, что с этим можно сделать.
Сейчас выбран трехчасовой шаг просто для того, чтобы визуально было не сильно шумно.

Думаю в будущем это действительно будет настройка.

**Comment by il77781** [comment]
@dimastark, спасибо за реакцию... 

Однако:
> Сейчас выбран трехчасовой шаг просто для того, чтобы визуально было не сильно шумно.

У меня сейчас вот так:
![Screenshot_2024-09-23-20-48-17-443_io homeassistant companion android](https://github.com/user-attachments/assets/8f933341-1055-4fcc-a40a-a1d15e2f6234)
Атрибуты у weather.yandex_pogoda вот такие:
```yaml
temperature: 10
apparent_temperature: 8
temperature_unit: °C
pressure_unit: mmHg
wind_bearing: 83
wind_gust_speed: 1.5
wind_speed: 0.8
wind_speed_unit: m/s
visibility_unit: km
precipitation_unit: mm
feelsLike: 8
windGust: 1.7
yandex_condition: CLEAR
forecast_icons:
  - https://yastatic.net/weather/i/icons/funky/png/dark/64/skc_n.png
  - https://yastatic.net/weather/i/icons/funky/png/dark/64/bkn_n.png
  - https://yastatic.net/weather/i/icons/funky/png/dark/64/bkn_d.png
  - https://yastatic.net/weather/i/icons/funky/png/dark/64/ovc.png
  - https://yastatic.net/weather/i/icons/funky/png/dark/64/bkn_n.png
forecast:
  - datetime: "2024-09-23T20:00:00+03:00"
    wind_bearing: 90
    native_wind_speed: 0.8
    native_apparent_temperature: 9
    native_temperature: 11
    condition: clear-night
    native_wind_gust_speed: 1.7
  - datetime: "2024-09-24T02:00:00+03:00"
    wind_bearing: 90
    native_wind_speed: 1
    native_apparent_temperature: 0
    native_temperature: 3
    condition: cloudy
    native_wind_gust_speed: 2
  - datetime: "2024-09-24T09:00:00+03:00"
    wind_bearing: 135
    native_wind_speed: 2.5
    native_apparent_temperature: 4
    native_temperature: 8
    condition: cloudy
    native_wind_gust_speed: 7.1
  - datetime: "2024-09-24T15:00:00+03:00"
    wind_bearing: 180
    native_wind_speed: 3
    native_apparent_temperature: 14
    native_temperature: 18
    condition: cloudy
    native_wind_gust_speed: 8.6
  - datetime: "2024-09-24T20:00:00+03:00"
    wind_bearing: 135
    native_wind_speed: 1.6
    native_apparent_temperature: 11
    native_temperature: 13
    condition: cloudy
    native_wind_gust_speed: 2.5
attribution: Data provided by Yandex Pogoda
entity_picture: https://yastatic.net/weather/i/icons/funky/png/dark/64/skc_n.png
friendly_name: Yandex Pogoda
supported_features: 2
```
Как видите, никакими тремя часами тут и не пахнет... Как я и говорил, разница 6-7-6-5 часов
Это только у меня так? Или я что-то делаю неправильно?

> Если ваш issue сейчас открыт, то вероятно, мы подумаем, что с этим можно сделать.

Это, конечно же, не может не обнадёживать... ) Просто хочется видеть реакцию по каждому из issue... Иначе просто не совсем понятно, обратили ли Вы какое-то внимание... )
